"""
LangGraph agent nodes for the supervisor-worker architecture.

FIXES APPLIED:
1. Analyst Node: SQL-free. Table selection and data loading both happen in
   deterministic Python (_select_table + DataLayer.get_full_table) BEFORE
   the model is ever called — no SQL is generated by the model anywhere in
   this pipeline anymore. The model only ever writes the pandas analysis
   code against a `df` that's already loaded with every column and every
   row of the correct table. See rulebase.md's ARCHITECTURE NOTE.
2. Thinker Node: Fixed guardrail ordering. Max iterations now forces 'report' explicitly.
   'extract' is only ever trusted when _diagnose_wrong_table deterministically
   confirms it (a KeyError on a column that's real on a DIFFERENT registered
   table) — the model's own 'extract' guess alone is never enough, the same
   way a hallucinated table name was never trusted under the old SQL design.
3. Report Node: Removed hallucinated follow-up questions. Strictly summarizes findings.
4. Analyst Node: Retry context echoes the previous Python back to the model
   alongside the error feedback, so it has something concrete to diverge
   from instead of regenerating the same mistake blind.
5. Rulebase: split into role-scoped '##' sections via get_rulebase_section().
   Each agent now receives only its own instructions instead of the entire
   file concatenated together — critical on a 4096-token model, where the
   old approach spent ~1700+ tokens of system prompt per call regardless of
   which agent was calling.
"""

import json
import logging
import re
import pandas as pd
from typing import TypedDict, List, Dict, Any, Optional
from datetime import datetime

from app.agent.model_client import ModelClient, _extract_json_fields_regex
from app.agent.sandbox_client import SandboxClient
from app.agent.data_layer import DataLayer
from app.config import RULEBASE_PATH

logger = logging.getLogger(__name__)


class AgentState(TypedDict):
    """State passed between nodes in the LangGraph."""
    query: str
    data_profile: Optional[Dict[str, Any]]
    table_names: List[str]
    schema_summary: Optional[str]
    conversation_history: List[Dict[str, str]]
    current_action: str
    generated_code: Optional[str]  # Python code only — no SQL phase anymore
    code_language: Optional[str]
    selected_table: Optional[str]  # Which registered table is loaded into `df`
    execution_result: Optional[Dict[str, Any]]
    findings: Optional[str]
    interpretation: Optional[str]
    final_response: Optional[str]
    iteration_count: int
    errors: List[str]
    artifacts: List[str]
    success: bool
    analyst_feedback: Optional[str]
    thinker_reason: Optional[str]


def load_rulebase() -> str:
    """Load the rulebase.md file as system prompt."""
    if RULEBASE_PATH.exists():
        content = RULEBASE_PATH.read_text()
        logger.info("Rulebase loaded from %s (%d chars)", RULEBASE_PATH, len(content))
        return content
    logger.warning("Rulebase not found at %s", RULEBASE_PATH)
    return ""

def _parse_max_iterations(rulebase_text: str, default: int = 6) -> int:
    m = re.search(r'Max iterations:\s*(\d+)', rulebase_text)
    return int(m.group(1)) if m else default


# Global cache for rulebase with file modification time tracking
_rulebase_cache = {"content": "", "mtime": 0.0}

def get_rulebase() -> str:
    """
    Get the current rulebase content, reloading if the file has changed.

    This enables hot-reloading: any edits to rulebase.md are picked up
    automatically on the next query without restarting the application.
    """
    global _rulebase_cache

    try:
        current_mtime = RULEBASE_PATH.stat().st_mtime if RULEBASE_PATH.exists() else 0.0

        if current_mtime != _rulebase_cache["mtime"]:
            # File has changed, reload it
            _rulebase_cache["content"] = load_rulebase()
            _rulebase_cache["mtime"] = current_mtime
            logger.info("Rulebase reloaded due to file change")

        return _rulebase_cache["content"]
    except Exception as e:
        logger.warning("Failed to check rulebase file status: %s", e)
        return _rulebase_cache["content"] or load_rulebase()


def get_agent_max_iterations() -> int:
    """Get the current max iterations from rulebase, with hot-reload support."""
    rulebase = get_rulebase()
    return _parse_max_iterations(rulebase)


def _parse_rulebase_sections(rulebase_text: str) -> Dict[str, str]:
    """
    Split the rulebase into named sections keyed by their '## name' header.

    Content before the first '##' header (title + preamble) is intentionally
    dropped here — it's documentation for humans editing the file, never
    meant to be sent to the model. A '###' sub-heading (e.g. "### Column
    Disambiguation") does NOT start a new top-level section; it stays inside
    whichever '##' section it's nested under.
    """
    sections: Dict[str, str] = {}
    current_name: Optional[str] = None
    current_lines: List[str] = []
    for line in rulebase_text.split('\n'):
        m = re.match(r'^##\s+(\S+)\s*$', line.strip())
        if m:
            if current_name:
                sections[current_name] = '\n'.join(current_lines).strip()
            current_name = m.group(1).strip().lower()
            current_lines = []
        elif current_name:
            current_lines.append(line)
    if current_name:
        sections[current_name] = '\n'.join(current_lines).strip()
    return sections


def get_rulebase_section(*names: str) -> str:
    """
    Return only the named section(s) of the rulebase, concatenated in the
    order given. This — NOT get_rulebase() — is what should be sent as the
    system prompt for a specific agent role: each role gets just its own
    instructions instead of every other role's prompt along with it, which
    matters a lot on a 4096-token model where the system prompt competes
    with the schema context and the completion budget for the same window.

    get_rulebase() (whole raw file) still exists and is still used for the
    max-iterations regex lookup, since that value isn't role-scoped.
    """
    sections = _parse_rulebase_sections(get_rulebase())
    parts = []
    for name in names:
        key = name.strip().lower()
        if key in sections:
            parts.append(sections[key])
        else:
            logger.warning("Rulebase section '%s' not found in rulebase.md", name)
    return '\n\n'.join(parts)

# Keyword -> subtype codes that must be SELECTed and SUMed together. Keep this
# in sync with the "SUBTYPE COLUMN GROUPS" block in rulebase.md's COLUMN
# GLOSSARY — that's the source of truth for a human reading the rulebase;
# this is the same rule re-expressed so it can be injected dynamically,
# right next to the query, rather than only living in the static system
# prompt where it competes with the schema block for the model's attention
# and is the first thing to fall out of a near-full context window.
_CATEGORY_SUBTYPE_GROUPS: List[tuple] = [
    (r'\btwo[\s-]*wheel', ['2WT', '2WN', '2WIC'], 'Two Wheeler'),
    (r'\bthree[\s-]*wheel', ['3WT', '3WN'], 'Three Wheeler'),
]


def _category_group_hint(query: str, table_columns: Dict[str, List[str]]) -> str:
    """
    If the query names a broad category that maps to more than one subtype
    column on the table(s) actually in play, return a concrete SELECT-all
    reminder. Only fires when 2+ of the group's codes are real columns here
    (so it stays silent on tables that don't have this subtype split).
    """
    all_cols = {c for cols in table_columns.values() for c in cols}
    hints = []
    for pattern, codes, label in _CATEGORY_SUBTYPE_GROUPS:
        if not re.search(pattern, query, re.IGNORECASE):
            continue
        present = [c for c in codes if c in all_cols]
        if len(present) > 1:
            hints.append(
                f'NOTE: the query asks about "{label}". On this table that total is '
                f'{present} SUMMED together. Your pandas code must select/sum ALL of '
                f'{present} — using only one of them is wrong.'
            )
    return '\n'.join(hints)


# Keyword -> distinguishing column for each specialized VAHAN dataset. Keep
# this in sync with the "dataset_manifest" section of rulebase.md, which is
# the human-readable source of truth for this same mapping — that section
# is no longer sent to the model (table selection isn't the model's job
# anymore), but a human editing the mapping should still only need to look
# in one place, the same way thinker_system_prompt rules 3-7 stay in sync
# with their code backstop below.
_TABLE_SELECTOR_KEYWORDS: List[tuple] = [
    (r'\bfuel\b', 'FUEL'),
    (r'\bmaker\b|\bmanufacturer\b', 'MAKER'),
    (r'\bnorms?\b|\bemission', 'NORMS'),
]


def _select_table(query: str, table_columns: Dict[str, List[str]]) -> str:
    """
    Deterministically choose which registered table to load in full for
    this query — matched by the column it contains (per rulebase.md's
    dataset_manifest), never by an assumed table name, since real table
    names are only known live at runtime via data_layer.get_table_names().

    This is a best-first-guess only. If it's wrong, the resulting KeyError
    is caught by _diagnose_wrong_table and thinker_node overrides
    'selected_table' on the retry. That two-way determinism — keyword
    guess going in, KeyError-driven correction coming back — is why there's
    no 'table' field in the analyst's JSON output: letting a 3B model name
    the table itself would reintroduce exactly the table-name hallucination
    this whole redesign removed from the old SQL phase.
    """
    query_lower = query.lower()
    for pattern, marker_col in _TABLE_SELECTOR_KEYWORDS:
        if re.search(pattern, query_lower):
            for table, cols in table_columns.items():
                if marker_col in cols:
                    return table
    # Default: the broadest/most general dataset (has VEHICLE_CLASS).
    for table, cols in table_columns.items():
        if 'VEHICLE_CLASS' in cols:
            return table
    # Last resort: whatever table is registered at all.
    return next(iter(table_columns), '')


def _format_single_table_schema(table_name: str, profile: Dict[str, Any]) -> str:
    """
    Render ONE table's profile as compact schema text for the analyst's
    context — scoped to just the table already loaded into `df`, rather
    than every registered table's combined schema_summary. Fewer distractor
    columns from tables the analyst doesn't have means fewer chances for
    the model to reference a column that belongs to the wrong table.
    """
    if 'error' in profile:
        return f"Table: user_data.{table_name} (profile error: {profile['error']})"
    lines = [f"Table: user_data.{table_name}", f"  Rows: {profile.get('row_count', '?')}", "  Columns:"]
    for col in profile.get('columns', []):
        lines.append(f"    - {col['name']} ({col['type']}): {col['distinct_count']} distinct")
        if col.get('sample_values'):
            lines.append(f"      Values: {', '.join(col['sample_values'])}")
    return "\n".join(lines)


def _diagnose_wrong_table(state: AgentState) -> Optional[Dict[str, str]]:
    """
    The one failure mode 'extract' still exists for now that there's no SQL
    phase: a KeyError on a column that isn't on the table currently loaded
    into `df`, but IS a real column on a DIFFERENT registered table — i.e.
    the deterministic _select_table guess was wrong for this query. Returns
    {'correct_table': ..., 'diagnosis': ...}, or None if this doesn't apply:

    - A KeyError on a column that's real on the CURRENT table's schema is a
      genuine Python bug, not a wrong table — stays 'analyze'.
    - A KeyError on a name that isn't a real column anywhere is a
      hallucinated name, not a wrong table — also stays 'analyze'. Never
      guess a table switch from a name that doesn't exist at all.
    """
    execution_result = state.get('execution_result') or {}
    err = str(execution_result.get('error') or '')
    m = re.search(r"KeyError:\s*'([^']+)'", err)
    if not m:
        return None
    missing_col = m.group(1)

    current_table = state.get('selected_table')
    data_profile = state.get('data_profile') or {}

    current_profile = data_profile.get(current_table) or {}
    current_cols = {c.get('name') for c in current_profile.get('columns', [])}
    if missing_col in current_cols:
        return None  # column WAS on the loaded table — a genuine Python bug

    for table_name, profile in data_profile.items():
        if table_name == current_table or not isinstance(profile, dict):
            continue
        if any(c.get('name') == missing_col for c in profile.get('columns', [])):
            return {
                'correct_table': table_name,
                'diagnosis': (
                    f"WRONG TABLE LOADED. Your code referenced '{missing_col}', which "
                    f"isn't on the currently loaded table ('{current_table}') but IS a "
                    f"real column on '{table_name}'. Reloading '{table_name}' — do not "
                    f"rename or guess a different column, '{missing_col}' is correct as "
                    f"written."
                ),
            }
    return None  # not a real column anywhere — hallucinated name, not a wrong table


def thinker_node(state: AgentState, model_client: ModelClient) -> AgentState:
    """
    FIX #2: Guardrail ordering fixed. Max iterations check happens LAST and overrides all.
    """
    iteration = state.get('iteration_count', 0)

    # Build context
    context_parts = [
        f"Query: {state['query']}",
        f"Available Tables: {state.get('table_names', [])}",
    ]

    if state.get('selected_table'):
        context_parts.append(f"Currently Loaded Table: {state['selected_table']}")

    if state.get('execution_result'):
        err = state['execution_result'].get('error')
        if err:
            context_parts.append(f"Last Error: {str(err)[:200]}")
        res = state['execution_result'].get('result_repr')
        if res:
            context_parts.append(f"Last Result: {res[:200]}")

    # Give the thinker the real diagnosis (not just the raw truncated
    # traceback) when we can determine one deterministically — it has been
    # observed inventing a plausible-sounding but factually wrong reason
    # otherwise (e.g. blaming a rename(column) typo that wasn't in the code).
    wrong_table = _diagnose_wrong_table(state)
    if wrong_table:
        context_parts.append(f"Diagnosis: {wrong_table['diagnosis']}")

    if state.get('generated_code'):
        context_parts.append(f"Last Python: {state['generated_code'][:100]}")

    context = "\n".join(context_parts)

    logger.info("=== THINKER INPUT ===\n%s", context)

    # Call LLM
    try:
        rulebase = get_rulebase_section('thinker_system_prompt')
        decision = model_client.thinker_decide(rulebase, context)
        logger.info("=== THINKER RAW OUTPUT ===\n%s", decision)
    except Exception as e:
        logger.error("Thinker LLM call failed: %s", e)
        decision = {'action': 'report', 'reason': 'LLM error'}

    action = decision.get('action', 'report')
    reason = decision.get('reason', '')

    # Guardrail 1: Validate action
    VALID = {'extract', 'analyze', 'visualize', 'report', 'done'}
    if action not in VALID:
        logger.warning("Invalid action '%s' from LLM, defaulting to report", action)
        action = 'report'

    # Guardrail 2: Handle failure retry (ONLY if not at max iterations)
    if not state.get('success') and action not in {'extract', 'analyze', 'report', 'done'}:
        action = 'analyze'

    # Guardrail 3: MAX ITERATIONS CHECK (HAPPENS LAST - OVERRIDES ALL)
    max_iterations = get_agent_max_iterations()
    if iteration >= max_iterations:
        logger.warning("Max iterations (%d) reached. Forcing 'report' to terminate.", max_iterations)
        action = 'report'  # Explicitly route to report to explain failure
        reason = "Max iterations reached"

    # Construct feedback in Python (NOT LLM)
    feedback = None
    selected_table_override = None
    if action in ('extract', 'analyze') and iteration < max_iterations:
        last_error = (state.get('execution_result') or {}).get('error', '')
        err_str_top = str(last_error) if last_error else ''

        # A crashed/killed sandbox process is never a schema or column
        # problem — with the full table always loaded now, it almost always
        # means the Python code materialized far more of it than it needed
        # to (e.g. .to_dict('records') on the whole un-aggregated table).
        # This is checked before the extract/analyze branches below
        # regardless of which action the thinker picked, because it has
        # been observed choosing 'extract' and inventing a plausible-
        # sounding schema fix for what was actually a crash — the crashed
        # table printed right above the claim clearly had those columns.
        # Don't let a wrong action choice lose this signal.
        if (
            'terminated unexpectedly' in err_str_top
            or 'Failed to write to sandbox' in err_str_top
            or 'Failed to read from sandbox' in err_str_top
        ):
            feedback = (
                "SANDBOX CRASHED. This is a resource/memory problem, not a "
                "schema problem — do not rename or guess at column names. "
                "The full table is already loaded into `df`: filter/select "
                "down to just the columns and rows the query needs as your "
                "FIRST step, before any groupby, pivot, or "
                "to_dict()/.values.tolist() call."
            )
            action = 'analyze'  # Force analyze since it's a Python/resource issue
        elif wrong_table:
            # Deterministic override: a KeyError that's confirmed against
            # the live schema to belong to a different real table. This is
            # the ONLY way 'extract' is ever trusted — never the model's
            # own say-so alone (rule 2: never guess schema).
            feedback = wrong_table['diagnosis']
            selected_table_override = wrong_table['correct_table']
            action = 'extract'
        elif err_str_top and 'SyntaxError' in err_str_top:
            feedback = (
                f"Your last code had a syntax error: {err_str_top[:150]}. "
                f"Do NOT include any print() debugging or inspection statements — "
                f"only code that computes `result` directly."
            )
            action = 'analyze'
        elif _is_python_exception(err_str_top):
            # ANY other Python exception = analyze, regardless of what the
            # LLM chose. There's no SQL to "fix" anymore — a KeyError not
            # confirmed as a wrong table (above) is always a Python bug.
            action = 'analyze'
            feedback = f"Code failed: {err_str_top[:200]}. Fix the Python code."
        elif action == 'extract':
            # The LLM said extract, but nothing deterministically confirms
            # a wrong table (wrong_table is None) — never trust that guess
            # alone. Route to analyze instead.
            action = 'analyze'
            feedback = (
                "No evidence the wrong table was loaded — the referenced "
                "column isn't a real column on any registered table, or the "
                "error doesn't point at a different table. Use only the "
                "columns shown in the schema for the currently loaded table."
            )
        elif err_str_top:
            feedback = f"Code failed: {err_str_top[:150]}. Fix the error."
        else:
            feedback = "Analyze the DataFrame using pandas."

    logger.info("Thinker Decision: action=%s, reason=%s", action, reason)

    print(f"Thinker Decision: action={action}, reason={reason}, feedback={feedback}")
    print(f"Iteration: {iteration}/{max_iterations}")

    result: AgentState = {
        'current_action': action,
        'thinker_reason': reason,
        'analyst_feedback': feedback,
        'iteration_count': iteration + 1,
    }
    if selected_table_override:
        result['selected_table'] = selected_table_override
    return result

def _is_python_exception(err_str: str) -> bool:
    """Check if the error string is a Python exception (KeyError, TypeError, etc.)."""
    if not err_str:
        return False
    python_exceptions = [
        'KeyError', 'TypeError', 'ValueError', 'AttributeError', 
        'IndexError', 'SyntaxError', 'NameError', 'ZeroDivisionError'
    ]
    return any(exc in err_str for exc in python_exceptions)


def _sanitize_python_code(code: str) -> str:
    """Strip markdown fences and import statements. No content-altering
    regex substitutions — those corrupt already-valid code."""
    code = code.strip()
    code = re.sub(r'^```(?:python)?\s*', '', code, flags=re.IGNORECASE)
    code = re.sub(r'\s*```$', '', code, flags=re.IGNORECASE)
    code = re.sub(r'^\s*(import|from)\s+\w.*$', '', code, flags=re.MULTILINE)
    return code.strip()


def _auto_close_brackets(code: str) -> str:
    """Append closing )/]/} for anything left open at EOF. Only appends —
    never removes/reorders — so it can't corrupt valid code."""
    import tokenize, io
    pairs = {'(': ')', '[': ']', '{': '}'}
    closers = {')': '(', ']': '[', '}': '{'}
    stack = []
    try:
        for tok in tokenize.generate_tokens(io.StringIO(code).readline):
            if tok.type == tokenize.OP:
                if tok.string in pairs:
                    stack.append(tok.string)
                elif tok.string in closers and stack and stack[-1] == closers[tok.string]:
                    stack.pop()
    except (tokenize.TokenError, IndentationError):
        pass
    if not stack:
        return code
    return code.rstrip() + ''.join(pairs[c] for c in reversed(stack)) + '\n'


def _flatten_indentation(code: str) -> str:
    """Strip leading whitespace from every line.

    Phase 2 analyst code is always a flat sequence of top-level pandas
    statements — the rulebase never asks for if/for/def blocks — so any
    indentation the model adds outside a bracket is spurious. That's
    exactly what produces 'unexpected indent' / IndentationError: a line
    has more indentation than the (nonexistent) enclosing block expects.
    Indentation inside an open ( [ { is unaffected by this either way,
    since Python's tokenizer ignores it there regardless.

    Caveat: if the code contains a multi-line triple-quoted string, this
    also strips leading whitespace from lines inside it, altering that
    string's content. That's an acceptable tradeoff for a last-resort
    repair — it only runs after the code has already failed to compile
    and bracket-repair hasn't fixed it, and it trades a possible content
    change for a working script over a guaranteed failure.
    """
    return '\n'.join(line.lstrip() for line in code.split('\n'))


def _validate_python(code: str) -> tuple[str, str | None]:
    """Returns (usable_code, error_or_None). If error is set, do NOT execute.

    Tries increasingly aggressive, non-destructive repairs before giving up:
    1. Compile as-is.
    2. Auto-close brackets left open at EOF.
    3. On top of that, flatten indentation (see _flatten_indentation) —
       covers 'unexpected indent' from stray leading whitespace.
    Returns the first candidate that compiles; if none do, returns the
    original code alongside the error from the last (most-repaired) attempt.
    """
    candidates = [code]

    bracket_fixed = _auto_close_brackets(code)
    if bracket_fixed != code:
        candidates.append(bracket_fixed)

    flattened = _flatten_indentation(bracket_fixed)
    if flattened not in candidates:
        candidates.append(flattened)

    last_error = None
    for candidate in candidates:
        try:
            compile(candidate, '<analyst>', 'exec')
            return candidate, None
        except SyntaxError as e:
            last_error = e
            continue

    return code, str(last_error)


def analyst_node(state: AgentState, model_client: ModelClient, sandbox: SandboxClient, data_layer: DataLayer) -> AgentState:
    """
    SQL-free execution:
    1. Deterministically pick (or reuse/override) which registered table to
       load in full — see _select_table / _diagnose_wrong_table. The only
       SQL that ever runs is DataLayer.get_full_table()'s fixed
       'SELECT * FROM user_data."{table}"', built from a table name that
       always comes from get_table_names(), never from model output.
    2. Call analyst_generate() for {python} only.
    3. Inject the already-loaded df into the sandbox and execute the Python.
    """
    iteration = state.get('iteration_count', 0)
    logger.info("=== ANALYST NODE START (Iteration %d) ===", iteration)

    table_names = state.get('table_names', [])
    data_profile = state.get('data_profile') or {}
    table_columns = {
        t: [c['name'] for c in data_profile[t].get('columns', [])]
        for t in table_names if t in data_profile
    }

    # 1. Table selection — deterministic, never asked of the model (see
    # rulebase.md's dataset_manifest and _select_table's docstring). A
    # prior 'extract' from thinker_node may have already overridden this in
    # state; otherwise reuse whatever was loaded last iteration, and only
    # run the keyword selector fresh on the very first call.
    selected_table = state.get('selected_table') or _select_table(state['query'], table_columns)
    if not selected_table:
        return {
            'errors': state.get('errors', []) + ['No table available to load'],
            'findings': 'No registered tables to analyze.',
            'success': False,
        }

    try:
        df = data_layer.get_full_table(selected_table)
    except Exception as e:
        logger.error("Failed to load table %s: %s", selected_table, e)
        return {
            'selected_table': selected_table,
            'errors': state.get('errors', []) + [f'Failed to load table {selected_table}: {e}'],
            'findings': f'Could not load table {selected_table}.',
            'success': False,
        }

    logger.info("Loaded table '%s' — shape %s", selected_table, df.shape)

    # 2. Build context for the analyst
    context_parts = []
    if state.get('analyst_feedback'):
        context_parts.append(f"FIX THIS FIRST: {state['analyst_feedback']}")

        # CRITICAL: without seeing what it actually wrote last time, the
        # model has nothing to diverge from. analyst_generate() is a
        # stateless call (system_prompt + this context string only — no
        # conversation history), so if we don't echo the previous attempt
        # back here, the model reconstructs a fresh query from the same
        # schema block + feedback description each retry and frequently
        # regenerates the exact same broken Python. Showing the prior code
        # explicitly gives it a concrete thing to change.
        prev_code = state.get('generated_code')
        if prev_code:
            context_parts.append(
                "YOUR PREVIOUS PYTHON (this is what caused the error above — "
                f"do not repeat it verbatim, write corrected code):\n{prev_code}"
            )

    context_parts.append(
        f"Loaded table: user_data.{selected_table} (ALL columns, ALL rows already in `df`)"
    )
    if data_profile.get(selected_table):
        context_parts.append(_format_single_table_schema(selected_table, data_profile[selected_table]))

    # Dynamic, per-query reminder placed immediately before the query text —
    # see _category_group_hint docstring for why this isn't left to the
    # static COLUMN GLOSSARY alone. Scoped to just the loaded table now,
    # same reasoning as _format_single_table_schema above.
    category_hint = _category_group_hint(
        state['query'], {selected_table: table_columns.get(selected_table, [])}
    )
    if category_hint:
        context_parts.append(category_hint)

    context_parts.append(f"Query: {state['query']}")

    context = "\n".join(context_parts)
    logger.info("=== ANALYST PROMPT CONTEXT ===\n%s", context[:1000])

    try:
        rulebase = get_rulebase_section('analyst_system_prompt')
        result = model_client.analyst_generate(rulebase, context)
        logger.info("=== ANALYST RAW OUTPUT ===\n%s", result)
    except Exception as e:
        logger.error("Analyst LLM call failed: %s", e)
        return {
            'selected_table': selected_table,
            'errors': state.get('errors', []) + [f'LLM error: {e}'],
            'findings': 'Code generation failed.',
            'success': False,
        }

    python_code = result.get('python', '')
    print(f"python_code: {python_code}")

    if not python_code:
        fallback = _extract_json_fields_regex(str(result), ['python'])
        if fallback:
            python_code = fallback.get('python', '')

    if not python_code.strip():
        return {
            'selected_table': selected_table,
            'generated_code': '',
            'findings': 'Analyst produced no Python — generation failed.',
            'errors': state.get('errors', []) + ['Empty analyst generation'],
            'success': False,
        }

    logger.info("Generated Python: %s", python_code[:200])

    # _sanitize_python_code strips markdown fences + import statements in
    # one pass (the sandbox has no __import__ available regardless — see
    # persistent_repl.py — so any import statement would fail anyway).
    python_code_cleaned = _sanitize_python_code(python_code)
    python_code_cleaned, syntax_error = _validate_python(python_code_cleaned)

    if syntax_error:
        logger.warning("Analyst Python failed to compile: %s", syntax_error)
        return {
            'selected_table': selected_table,
            'generated_code': python_code,
            'execution_result': {'error': f'SyntaxError: {syntax_error}'},
            'findings': f"Generated Python failed to parse: {syntax_error}",
            'errors': state.get('errors', []) + [f'SyntaxError: {syntax_error}'],
            'success': False,
        }

    # Serialize df for injection into the sandbox as a plain Python literal
    # — NOT via `import json`. repr() of a list of dicts is valid Python
    # source by itself, so no import/parsing call is needed at exec time.
    df_safe = df.copy()
    for col in df_safe.columns:
        if pd.api.types.is_datetime64_any_dtype(df_safe[col]):
            df_safe[col] = df_safe[col].astype(str)
    # Replace NaN/NaT with None so repr() emits valid Python literals.
    # repr(float('nan')) is the bare word `nan`, which is not valid Python
    # syntax on its own and would raise NameError at exec time.
    df_safe = df_safe.astype(object).where(pd.notnull(df_safe), None)
    df_records = df_safe.to_dict(orient='records')
    bootstrap_code = f"df = pd.DataFrame({df_records!r})\n"
    schema_check = "print('COLUMNS:', df.columns.tolist())\n"
    full_code = bootstrap_code + schema_check + "\n" + python_code_cleaned

    logger.debug("Full code sent to sandbox (first 500 chars): %s", full_code[:500])
    execution_result = sandbox.execute(full_code, timeout=30)

    if execution_result.get('error'):
        logger.warning("Execution failed: %s", execution_result['error'])
        return {
            'selected_table': selected_table,
            'generated_code': python_code,
            'code_language': 'python',
            'execution_result': execution_result,
            'findings': f"Execution failed: {execution_result['error']}",
            'errors': state.get('errors', []) + [execution_result['error']],
            'success': False,
        }

    findings = execution_result.get('result_repr', 'Analysis complete.')
    print(f"Execution Result: {execution_result}")
    print(f"Findings: {findings}")

    return {
        'selected_table': selected_table,
        'generated_code': python_code,
        'code_language': 'python',
        'execution_result': execution_result,
        'findings': findings,
        'success': True,
    }


def data_fetch_node(state: AgentState, data_layer: DataLayer) -> AgentState:
    """Data fetch node: Load dataset schema and profile tables."""
    logger.info("Running data_fetch_node")

    if state.get('data_profile') is not None:
        logger.debug("Data already fetched, skipping")
        return {}

    try:
        table_names = data_layer.get_table_names()
    except Exception as e:
        logger.error("Failed to get table names: %s", e)
        return {'errors': state.get('errors', []) + [f'Failed to list tables: {e}'], 'table_names': []}

    if not table_names:
        logger.warning("No tables found in dataset")
        return {'errors': state.get('errors', []) + ['No tables found in dataset'], 'table_names': []}

    logger.info("Found %d tables: %s", len(table_names), table_names)

    profiles = {}
    for table_name in table_names:
        try:
            profiles[table_name] = data_layer.get_profile(table_name)
        except Exception as e:
            logger.error("Failed to profile table %s: %s", table_name, e)
            profiles[table_name] = {'error': str(e)}

    summary_parts = []
    for table_name, profile in profiles.items():
        if 'error' in profile:
            continue
        summary_parts.append(f"Table: user_data.{table_name}")
        summary_parts.append(f"  Rows: {profile['row_count']}")
        summary_parts.append("  Columns:")
        for col in profile['columns']:
            summary_parts.append(f"    - {col['name']} ({col['type']}): {col['distinct_count']} distinct")
            if col.get('sample_values'):
                summary_parts.append(f"      Values: {', '.join(col['sample_values'])}")

    schema_summary = "\n".join(summary_parts)
    logger.info("Data fetch complete, schema summary: %d chars", len(schema_summary))

    return {
        'data_profile': profiles,
        'table_names': table_names,
        'schema_summary': schema_summary,
        'conversation_history': state.get('conversation_history', []) + [{
            'role': 'system', 'content': f"Dataset loaded:\n{schema_summary}"
        }]
    }


def viz_node(state: AgentState, model_client: ModelClient, sandbox: SandboxClient) -> AgentState:
    """Visualization node: Generate matplotlib charts from findings."""
    logger.info("Running viz_node")

    findings = state.get('findings', 'No findings available.')
    query = state.get('query', 'Unknown query')

    task_description = (
        f"You are a visualization expert. Write Python matplotlib code to chart these findings.\n\n"
        f"Query: {query}\nFindings:\n{findings}\n\n"
        f"Create a clear, professional chart. Save it to /scratch/chart.png"
    )

    data_context = "Use matplotlib for plotting. Save figures to /scratch/ directory."

    rulebase = get_rulebase_section('viz_system_prompt')
    code_result = model_client.generate_code(rulebase, task_description, data_context)
    logger.info("Viz model response: %s", code_result)

    code = code_result.get('code', '')
    language = code_result.get('language', 'python')

    if not code:
        logger.warning("Viz code generation returned empty code")
        return {'errors': state.get('errors', []) + ['Failed to generate visualization code'], 'generated_code': None}

    # Strip markdown code fences from LLM output (common issue)
    # First strip leading/trailing whitespace, then remove fences
    code_stripped = code.strip()
    code_cleaned = re.sub(r'^```(?:python)?\s*', '', code_stripped, flags=re.IGNORECASE)
    code_cleaned = re.sub(r'\s*```$', '', code_cleaned, flags=re.IGNORECASE)
    code_cleaned = code_cleaned.strip()

    logger.info("Generated viz code (cleaned):\n%s", code_cleaned[:500])

    execution_result = sandbox.execute(code_cleaned, timeout=30)
    new_artifacts = execution_result.get('artifacts', [])

    if execution_result.get('error'):
        logger.warning("Viz execution failed: %s", execution_result.get('error'))
    else:
        logger.info("Viz execution succeeded, artifacts: %s", new_artifacts)

    print(f"Viz Execution Result: {execution_result}")
    return {
        'generated_code': code,
        'code_language': language,
        'execution_result': execution_result,
        'artifacts': state.get('artifacts', []) + new_artifacts,
        'conversation_history': state.get('conversation_history', []) + [{
            'role': 'assistant', 'content': f"Visualization: Generated chart. Artifacts: {new_artifacts}"
        }]
    }


def report_node(state: AgentState, model_client: ModelClient) -> AgentState:
    """
    FIX #3: Reporting node strictly summarizes findings.
    NO hallucinated follow-up questions or next steps.
    """
    logger.info("Running report_node")

    findings = state.get('findings', 'No findings available.')
    errors = state.get('errors', [])
    query = state.get('query', 'Unknown query')

    # Build honest interpretation
    table_names = state.get('table_names', ['the dataset'])

    if errors:
        interpretation = f"Analysis of {', '.join(table_names)} encountered issues: {', '.join(errors[-2:])}. Findings: {findings[:200]}"
    else:
        interpretation = f"Based on analysis of {', '.join(table_names)}: {findings[:500]}"

    logger.info("Report Interpretation Context: %s", interpretation)

    # Generate response (No follow-up questions instruction)
    try:
        rulebase = get_rulebase_section('report_system_prompt')
        response = model_client.generate_response(
            system_prompt=rulebase,
            query=query,
            findings=findings,
            interpretation=interpretation
        )
        logger.info("=== REPORT GENERATED ===\n%s", response)
    except Exception as e:
        logger.error("Report generation failed: %s", e)
        response = f"Unable to generate final report due to error: {e}. Raw findings: {findings}"

    return {
        'findings': findings,
        'interpretation': interpretation,
        'final_response': response,
        'current_action': 'done',
        'conversation_history': state.get('conversation_history', []) + [{
            'role': 'assistant', 'content': f"Report: {response[:500]}"
        }]
    }